version: '3.4'

services:
  application-api:
    image: rpi/rpibuttons-api
    ports:
      - "5100:8080"

  application-app:
    image: rpi/rpibuttons-app
    environment:
      - API_HOST=application-api
      - API_PROTOCOL=http
      - API_PORT=5100
    devices:
      - /dev/gpiomem:/dev/gpiomem
    depends_on:
      - application-api