version: '3.4'

services:
  application-api:
    image: rpi/rpibuttons-api
    # ports:
    #   - "8080:8080"
    expose:
      - "8080"

  application-app:
    image: rpi/rpibuttons-app
    environment:
      - API_HOST=application-api
      - API_PROTOCOL=http
      - API_PORT=8080
    devices:
      - /dev/gpiomem:/dev/gpiomem
      - /dev/i2c-1:/dev/i2c-1
    depends_on:
      - application-api